### ISSUE TITLE
Focused window at the top

### ISSUE THREAD

**Issue by mr-cheffy** [STRML/react-draggable#660]
Is there a way to make the draggable component be on top of other draggable components when clicking or focusing them?

**Comment by Tpleme** [comment]
I've manage to make something by working with z-index.
You can get a ref to the component and use the method o Start to change the z-index of the component and then have a click outside listener that chances the z index to a lower number.

With this when you start dragging the component gets a z-index big enough to be on top and if you click anything else it will reverse this.

This is not the solution because if you are working with multiple windows it could be difficult to manage.
